export const images = {
  logo: "/images/logo-einssein.png",
  hero: "/images/logm3Y6noXAAbYC4b5K7uc0A.jpeg",
  ogPreview: "/images/TTfok0BW6NcfIWkj0q9sTwv2XU.jpeg",
  campTents: "/images/Yafp9oPmEMV7UUL8EyQokUpMABo.jpg",
  activityDance: "/images/bOdQ2QzNVr0cexlPfA2i4sYS6k8.jpg",
  activityTheater: "/images/umj7A0bALig44SDxGE2Le2zvJOo.jpeg",
  activityGarden: "/images/lxuTiMs23mSoZgGAQkec3GUhr5g.jpg",
  gradientBubble: "/images/2D2Eq1zgnc5pDzEi95NENlTy6oQ.jpg",
  gradientShapes: "/images/b5BAXAQCSX9uo7JqPHBYYsrzQ.jpg",
  gradientSilk: "/images/apiN3w7ZPEnLDHVeUxa1Br6TVNk.jpg",
  partnerSpline: "/images/IEmMUeO1Sr6GcrqbuzBib4pKMN0.png",
  partnerFamilienzentrum: "/images/pYGGe58W5cybNNSDt0JDhfqlr8.png",
  partnerBahai: "/images/VPKdx55Znox4u3oGCqyq7WsZWlk.png",
  partnerSsv: "/images/ctgUWPe2FeKeRk4ZuRYlMoqtL34.png",
  partnerStadt: "/images/bAkqCOmdHp58PmavO7lVQd5BqOo.png",
  partnerFeuerwehr: "/images/RLJ6rqRsdK9LX18PhFk9ujyI.png",
  partnerPeoplesTheater: "/images/wfi8stXVu4WLikkOxaCoILKYEg.png",
  partnerExtra1: "/images/AzgAX2OfkG4Ok078ncI0CKS30oo.png",
  partnerExtra2: "/images/LbxuS4gEtakUMtvcMQCHaRZMcqM.png",
  partnerExtra3: "/images/OcXHNM1Uwy8YFXgHUAYNbbn3E.png",
  partnerExtra4: "/images/RifHn7qSHYhpFt2W9RN1D7NAWi0.png",
  partnerExtra5: "/images/TBimFs1YsT1mJ0drpVDHLptNI.png",
  partnerExtra6: "/images/w1IKhqUUp4VKzgNBcdME9xca0.png",
  partnerExtra7: "/images/wrpSu91ciE5C2v1w0iGK4vCNQQ.png",
  partnerExtra8: "/images/PyuRYejhSWeJJmQ2CusFUwXgPU.png",
  partnerExtra9: "/images/fN12Y24VuMhOOWtztvassUZ8M.png",
} as const;
